# Generated by Django 4.0.6 on 2022-07-11 11:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_aboutmodel_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
