# Generated by Django 4.0.6 on 2022-07-11 21:04

import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_aboutmodel_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=4), django.core.validators.MaxLengthValidator(limit_value=30)]),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='phone',
            field=models.CharField(max_length=13, validators=[config.validators.PhoneValidator()]),
        ),
    ]
