# Generated by Django 4.0.6 on 2022-07-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aboutmodel_body_ru_aboutmodel_body_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
