# Generated by Django 4.0.6 on 2022-07-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aboutmodel_title_aboutmodel_title_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='title_uz',
        ),
    ]
