# Generated by Django 4.0.6 on 2022-07-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_aboutmodel_title_remove_aboutmodel_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
