# Generated by Django 4.0.6 on 2022-07-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_aboutmodel_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutModel',
        ),
    ]
