# Generated by Django 4.0.6 on 2022-07-12 14:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_imgage_aboutmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeAboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='me')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.DeleteModel(
            name='AboutModel',
        ),
    ]
