# Generated by Django 4.0.6 on 2022-07-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_meaboutmodel_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meaboutmodel',
            old_name='img1',
            new_name='image',
        ),
    ]
