# Generated by Django 4.0.6 on 2022-07-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_img1_meaboutmodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeAboutModel',
        ),
    ]
